 
export const CHANGESTATUSLOGIN = 'CHANGESTATUSLOGIN';
export const CHANGESEARCHSTAFF = 'CHANGESEARCHSTAFF';
export const CHANGESEARCHPROJECTUSER = 'CHANGESEARCHPROJECTUSER';
export const CHECKPASSWORDCURRENT = 'CHECKPASSWORDCURRENT';
export const CHANGEPASSAFLOG = 'CHANGEPASSAFLOG';
export const CHECKPASSCONFIRM = 'CHECKPASSCONFIRM';
